### ISSUE TITLE
Invalid Link for Pretrained Model

### ISSUE THREAD

**Issue by abdullah-shwaiky** [ymoslem/Arabisc#4]
Clicking on the download link for the pre-trained model returns Access Denied. Could the download link be updated? Thank you!

**Comment by AliAlWahayb** [comment]
any updates?

**Comment by abdullah-shwaiky** [comment]
Unfortunately not.

**Comment by ymoslem** [comment]
The updated link can be found [here](https://github.com/ymoslem/Arabisc/releases/download/v1.0/model-spell.zip).
